### ISSUE TITLE
USER STORY: As a developer I want to be able to store my code in a Github Repository so that I can collaborate with others

### ISSUE THREAD

**Issue by VCGithubCode** [VCGithubCode/Gratidudes#1]
EPIC: Create Repository

As a developer on The Gratidudes hackathon team, I would like to be able to have a place to store my code for version control and collaboration with my teammates.

**Acceptance Criteria**

- Repository created on Github

- Availability for users on either Gitpod or VSCode to be able to clone the project, work on it locally, and push their changes to the main repo for review and possible adaptation into main code

- Ability for developers to be able to fork, create branches, create pull requests, and see the project kanban board

**Tasks**

- [x] Task 1: Create Repo
- [x] Task 2: Make initial commit with necessary dependencies
- [x] Task 3:  Inform teammates of repo location
- [x] Task 4:  Create Project and categories
- [x] Task 5: Start creating Epic template
